[package]
name = "unibo-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Your Name"]
license = "GPL-0.3-or-later"
description = "Unofficial Thesis cover and document template for the University of Bologna"
repository = "https://github.com/soliprem/unibo-thesis-template"
keywords = ["thesis", "university", "bologna", "academia"]

[template]
path = "template"
entrypoint = "main.typ"
# thumbnail = "thumbnail.png"
